version: 0.5
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g typescript
      - npm install
  build:
    commands:
      - echo Build starting
      - npm run build
  post_build:
    commands:
      - echo Build completed
cache:
  paths:
    - 'node_modules/**/*'
artifacts:
  files:
    - '**/*'
  name: Mockingbird-build-$(date +%Y-%m-%d)
